export const eventsStore = [
  {
    title: "Day Trading Idea and Strategyt",
    date: "Mon, Mar 18 · 7:00 PM PDT",
    image: "./images/events-images/img1.png",
    type: "offline",
    attendees: 1,
    category: "Business",
    distance: 5,
  },
  {
    title: "Let's Talk Networking: JPMorgan Chase in Palo Alto",
    date: "Tue, Mar 19 · 5:00 PM PDT",
    image: "./images/events-images/img2.png",
    type: "offline",
    attendees: 41,
    category: "Business",
    distance: 25,
  },
  {
    title:
      "Tech Talks & Quiz: Next- Gen Database Solutions for Emerging Use Cases",
    date: "Wed, Mar 13 · 6:00 PM PDT",
    image: "./images/events-images/img3.png",
    type: "offline",
    category: "Technology",
    distance: 40,
    attendees: 40,
  },
  {
    title: "INFORMS San Francisco Chapter In-Person Event",
    date: "Thu, Mar 28 · 5:00 PM PDT",
    image: "./images/events-images/img4.png",
    type: "offline",
    attendees: 41,
    category: "Health and Wellbeing",
    distance: 50,
  },
  {
    title: "AI Wednesdays - Meet and Greet!",
    date: "Wed, Mar 13 · 6:30 PM PDT",
    image: "./images/events-images/img5.png",
    type: "offline",
    attendees: 29,
    category: "Technology",
    distance: 5,
  },
  {
    title: "ROS By-The-Bay March  2024",
    date: "Thu, Mar 21 · 6:00 PM PDT",
    image: "./images/events-images/img6.png",
    type: "offline",
    distance: 15,
    category: "Social Activities",
    attendees: 51,
  },
  {
    title: "Free Christian Singles' Dinner",
    date: "Fri, Mar 29 · 6:00 PM PDT",
    image: "./images/events-images/img7.png",
    type: "offline",
    distance: 10,
    category: "Hobbies and Passions",
    attendees: 11,
  },
  {
    title: "In-person: Deep Dive into  RAG Architectures (Food served)",
    date: "Thu, Mar 14 · 5:00 PM PDT",
    image: "./images/events-images/img8.png",
    type: "offline",
    distance: 50,
    category: "Hobbies and Passions",
    attendees: 16,
  },
  {
    title: "Amazing On-Demand 15  Min Interviews with Top  Coaches and Speakers",
    date: "Thu, Mar 14 · 6:00 PM PDT",
    image: "./images/events-images/img9.png",
    type: "online",
    distance: 25,
    category: "Business",
    attendees: 3,
  },
  {
    title: "Vision Pro Developers  Online Meetup",
    date: "Wed, Mar 13 · 7:00 PM PDT",
    image: "./images/events-images/img10.png",
    type: "online",
    category: "Technology",
    attendees: 3,
  },
  {
    title: "Significant Musical Moments",
    date: "Wed, Mar 13 · 6:00 PM PDT",
    image: "./images/events-images/img11.png",
    type: "online",
    category: "Hobbies and Passions",
    attendees: 16,
    distance: 10,
  },
  {
    title: "FREE Webinar: Introduction to Power BI",
    date: "Thu, Mar 14 · 5:30 PM PDT",
    image: "./images/events-images/img12.png",
    type: "online",
    category: "Technology",
    attendees: 33,
  },
];

